// ==UserScript==
// @name         TU Chaos Marbles
// @namespace    https://github.com/RelaxSweety/Torn-Scripts
// @version      0.2.0
// @description  Online multiplayer marble race for 2-4 players
// @match        https://www.torn.com/*
// @grant        GM_xmlhttpRequest
// @connect      tu-multiplayer-server.tuserver.workers.dev
// @run-at       document-idle
// @updateURL    https://raw.githubusercontent.com/RelaxSweety/Torn-Scripts/main/torn-utilities/modules/chaos-marbles.user.js
// @downloadURL  https://raw.githubusercontent.com/RelaxSweety/Torn-Scripts/main/torn-utilities/modules/chaos-marbles.user.js
// ==/UserScript==
(()=>{'use strict';
const ID="chaos-marbles",KEY="tu:chaos-marbles:game",HISTORY="tu:chaos-marbles:history";
const COLORS=["#dc6059","#e4b951","#5fb2da","#8fd17b"],NAMES=["Crimson","Gold","Azure","Emerald"];
let panel=null,game=null,notice="",view="play",active=false,session=null,timer=null,busy=false;const API="https://tu-multiplayer-server.tuserver.workers.dev/api/marbles",SESSION="tu:chaos-marbles:session";
const E=(tag,parent,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;parent.append(e);return e};
const B=(parent,label,fn)=>{const b=E("button",parent,label);b.type="button";b.onclick=fn;b.style.cssText="background:#344154;color:#fff;border:1px solid #657184;border-radius:6px;padding:8px 10px;cursor:pointer;font:inherit";return b};
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}};
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(game))}catch{}};

const save=()=>{if(session)localStorage.setItem(SESSION,JSON.stringify(session));else localStorage.removeItem(SESSION)};
function legal(p,i,roll){if(!game||roll===null)return false;const v=game.marbles[p][i];if(v===35)return false;const dest=v===-1?(roll===6?0:-1):v+roll;return dest>=0&&dest<=35&&!game.marbles[p].some((x,j)=>j!==i&&x===dest)}
function choices(){return !game||!session||game.turn!==session.player?[]:game.marbles[session.player].map((_,i)=>i).filter(i=>legal(session.player,i,game.roll))}
function req(path,method="GET",body){const url=API+path,headers={"Content-Type":"application/json"};if(session?.token)headers.Authorization="Bearer "+session.token;const data=method==="POST"?JSON.stringify(body||{}):undefined;
const parse=(status,raw)=>{let o;try{o=JSON.parse(raw)}catch{throw Error("Invalid server response")};if(status<200||status>=300)throw Error(o.error||"Server error");return o};
return new Promise((resolve,reject)=>{if(typeof GM_xmlhttpRequest==="function"){GM_xmlhttpRequest({method,url,headers,data,timeout:12000,onload:r=>{try{resolve(parse(r.status,r.responseText))}catch(e){reject(e)}},onerror:()=>reject(Error("Network error")),ontimeout:()=>reject(Error("Request timed out"))})}else fetch(url,{method,headers,body:data,cache:"no-store"}).then(async r=>parse(r.status,await r.text())).then(resolve,reject)})}
function recordResult(){if(game?.winner===null||!session)return;const h=read(HISTORY,[]);if(h.some(x=>x.room===session.room))return;h.unshift({room:session.room,winner:game.winner,player:session.player,count:game.count,moves:game.moves,rolls:game.rolls,ended:new Date().toISOString()});localStorage.setItem(HISTORY,JSON.stringify(h.slice(0,100)))}
async function action(path,method="GET",body,join=false){if(busy)return;busy=true;try{const r=await req(path,method,body);if(join){session={room:r.room,token:r.token,player:r.player};save()}game=r.game;recordResult();notice="Room "+session.room+" updated";render()}catch(e){notice=e.message;render()}finally{busy=false}}
function roll(){if(session&&game?.turn===session.player&&game.roll===null)action("/"+session.room+"/roll","POST")}
function move(i){if(session&&game?.turn===session.player&&legal(session.player,i,game.roll))action("/"+session.room+"/move","POST",{index:i})}
function drawBoard(parent){const wrap=E("div",parent);wrap.style.cssText="border:3px solid #d6b96a;background:#121b25;border-radius:10px;padding:5px;margin:10px auto;max-width:420px;box-sizing:border-box";const svg=document.createElementNS("http://www.w3.org/2000/svg","svg");svg.setAttribute("viewBox","0 0 400 400");svg.style.cssText="display:block;width:100%;aspect-ratio:1";wrap.append(svg);
const node=(name,attrs)=>{const n=document.createElementNS("http://www.w3.org/2000/svg",name);for(const [k,v] of Object.entries(attrs))n.setAttribute(k,v);svg.append(n);return n};
node("circle",{cx:200,cy:200,r:153,fill:"none",stroke:"#455363","stroke-width":2});
for(let i=0;i<32;i++){const a=-Math.PI/2+i*Math.PI*2/32,x=200+153*Math.cos(a),y=200+153*Math.sin(a);node("circle",{cx:x,cy:y,r:15,fill:i%8===0?COLORS[i/8]:"#293747",stroke:"#708092","stroke-width":1.5})}
for(let p=0;p<game.count;p++){const a=-Math.PI/2+p*Math.PI/2;for(let j=0;j<4;j++){const r=120-j*24;node("circle",{cx:200+r*Math.cos(a),cy:200+r*Math.sin(a),r:10,fill:COLORS[p],opacity:.35,stroke:"#ddd","stroke-width":1})}}
node("circle",{cx:200,cy:200,r:31,fill:"#253344",stroke:"#d6b96a","stroke-width":2});const t=node("text",{x:200,y:205,"text-anchor":"middle",fill:"#f0d68d","font-size":13,"font-weight":"bold"});t.textContent="CHAOS";
for(let p=0;p<game.count;p++){for(let i=0;i<3;i++){const v=game.marbles[p][i];let x,y;if(v===-1){const a=-Math.PI/2+p*Math.PI/2;const bx=200+100*Math.cos(a),by=200+100*Math.sin(a);x=bx+(i-1)*13*Math.cos(a+Math.PI/2);y=by+(i-1)*13*Math.sin(a+Math.PI/2)}else if(v<32){const a=-Math.PI/2+((p*8+v)%32)*Math.PI*2/32;x=200+153*Math.cos(a);y=200+153*Math.sin(a)}else{const a=-Math.PI/2+p*Math.PI/2,r=120-(v-32)*24;x=200+r*Math.cos(a);y=200+r*Math.sin(a)}
const c=node("circle",{cx:x,cy:y,r:9,fill:COLORS[p],stroke:"#fff","stroke-width":2});if(session&&p===session.player&&p===game.turn&&game.roll!==null&&legal(p,i,game.roll)){c.style.cursor="pointer";c.setAttribute("stroke-width","4");c.addEventListener("click",()=>move(i))}
const label=node("text",{x,y:y+3.5,"text-anchor":"middle",fill:"#121820","font-size":10,"font-weight":"bold","pointer-events":"none"});label.textContent=i+1}}
}

function historyPage(parent){const h=read(HISTORY,[]);E("strong",parent,"Completed games on this device: "+h.length);E("p",parent,"Your wins: "+h.filter(x=>x.winner===x.player).length);if(!h.length)E("p",parent,"No completed games yet.");for(const x of h.slice(0,30)){const row=E("div",parent,new Date(x.ended).toLocaleString()+" | Room "+x.room+" | "+NAMES[x.winner]+" won | "+x.moves+" moves | You: "+NAMES[x.player]);row.style.cssText="border-bottom:1px solid #465466;padding:7px 0;font-size:12px"}}
function render(){if(!panel)return;const body=panel.querySelector(".body");body.replaceChildren();const tabs=E("div",body);tabs.style.cssText="display:flex;gap:6px;flex-wrap:wrap;margin:8px 0";B(tabs,"Play",()=>{view="play";render()});B(tabs,"Game History",()=>{view="history";render()});if(view==="history"){historyPage(body);return}
if(!session){E("p",body,"Online multiplayer for 2–4 players. Each player joins from their own device. Roll 6 to leave Waiting for Chaos.");const controls=E("div",body);controls.style.cssText="display:flex;gap:6px;flex-wrap:wrap";const input=E("input",controls);input.placeholder="ROOM CODE";input.maxLength=6;input.style.cssText="width:115px;padding:7px";B(controls,"Join",()=>{const c=input.value.trim().toUpperCase();if(!/^[A-HJ-NP-Z2-9]{6}$/.test(c)){notice="Invalid room code";render();return}action("/"+c+"/join","POST",{},true)});for(let n=2;n<=4;n++)B(body,"Create "+n+"-player room",()=>action("","POST",{count:n},true));E("p",body,notice);return}
const header=E("div",body);header.style.cssText="padding:8px;background:#293747;border-radius:6px";header.textContent="Room: "+session.room+" | You: "+NAMES[session.player];const controls=E("div",body);controls.style.cssText="display:flex;gap:7px;flex-wrap:wrap;margin:8px 0";B(controls,"Copy Invite",()=>{const text="Join TU Chaos Marbles room "+session.room; if(navigator.clipboard?.writeText)navigator.clipboard.writeText(text).catch(()=>{});else notice=text});B(controls,"Leave",()=>{session=null;game=null;save();render()});B(controls,"Refresh",()=>action("/"+session.room+"/state"));
if(!game){E("p",body,"Loading room...");return}
const ready=game.ready;const status=E("div",body);status.style.cssText="padding:8px;border-radius:6px;background:#293747";status.textContent=game.winner!==null?NAMES[game.winner]+" wins!":!ready?"Waiting for Chaos: "+game.players.filter(Boolean).length+"/"+game.count+" players joined":game.turn===session.player?"Your turn — "+(game.roll===null?"roll the die":"move a marble (roll "+game.roll+")"):NAMES[game.turn]+"'s turn";
E("p",body,notice).style.fontSize="12px";E("div",body,"Waiting for Chaos — marbles staged outside the home lanes").style.cssText="font-size:12px;color:#d6b96a;text-align:center";drawBoard(body);
const moves=E("div",body);moves.style.cssText="display:flex;gap:6px;flex-wrap:wrap";const die=B(moves,"Roll die",roll);die.disabled=!ready||game.winner!==null||game.turn!==session.player||game.roll!==null||busy;
if(ready&&game.turn===session.player&&game.roll!==null)for(const i of choices())B(moves,"Move marble "+(i+1),()=>move(i));
E("p",body,"Moves: "+game.moves+" | Rolls: "+game.rolls+" | Home: "+game.marbles.map((a,p)=>NAMES[p]+" "+a.filter(x=>x===35).length+"/3").join(" · ")).style.fontSize="12px";
E("p",body,"Rules: Roll 6 to enter. Exact roll required to finish. Capture opponents by landing on them. A 6 earns another roll.").style.fontSize="12px"}
function activate({mount,close}){if(panel)return;panel=E("section",mount);panel.style.cssText="position:fixed;left:50%;top:50%;transform:translate(-50%,-50%);z-index:2147483647;background:#20252e;color:#fff;border:1px solid #888;border-radius:12px;padding:15px;width:min(390px,94vw);height:min(690px,85vh);min-width:260px;min-height:320px;max-width:96vw;max-height:92vh;overflow:auto;resize:both;box-sizing:border-box;font:14px system-ui";
const bar=E("div",panel);bar.style.cssText="display:flex;justify-content:space-between;align-items:center;gap:8px;margin-bottom:10px;touch-action:none;user-select:none;cursor:move";E("strong",bar,"Chaos Marbles");const min=B(bar,"−",close);min.title="Minimize to TU";min.style.cssText+=";font-size:22px;font-weight:bold;padding:0 12px;line-height:30px";
let drag=null;bar.addEventListener("pointerdown",e=>{if(e.target.closest("button"))return;const r=panel.getBoundingClientRect();drag={x:e.clientX,y:e.clientY,l:r.left,t:r.top};panel.style.transform="none";panel.style.left=r.left+"px";panel.style.top=r.top+"px";bar.setPointerCapture(e.pointerId)});bar.addEventListener("pointermove",e=>{if(!drag)return;panel.style.left=Math.max(0,Math.min(innerWidth-100,drag.l+e.clientX-drag.x))+"px";panel.style.top=Math.max(0,Math.min(innerHeight-60,drag.t+e.clientY-drag.y))+"px"});bar.addEventListener("pointerup",()=>drag=null);bar.addEventListener("pointercancel",()=>drag=null);
const grip=E("div",panel,"◢");grip.style.cssText="position:absolute;right:3px;bottom:2px;width:30px;height:30px;display:flex;align-items:end;justify-content:end;padding:3px;box-sizing:border-box;cursor:nwse-resize;touch-action:none;color:#d6b96a;font-size:21px";let resize=null;grip.onpointerdown=e=>{e.preventDefault();const r=panel.getBoundingClientRect();resize={x:e.clientX,y:e.clientY,w:r.width,h:r.height,l:r.left,t:r.top};panel.style.transform="none";panel.style.left=r.left+"px";panel.style.top=r.top+"px";grip.setPointerCapture(e.pointerId)};grip.onpointermove=e=>{if(!resize)return;panel.style.width=Math.max(260,Math.min(innerWidth-resize.l-8,resize.w+e.clientX-resize.x))+"px";panel.style.height=Math.max(320,Math.min(innerHeight-resize.t-8,resize.h+e.clientY-resize.y))+"px"};grip.onpointerup=()=>resize=null;grip.onpointercancel=()=>resize=null;
E("div",panel).className="body";session=read(SESSION,null);render();if(session)action("/"+session.room+"/state");timer=setInterval(()=>{if(session&&!busy&&panel)action("/"+session.room+"/state")},2500)}
function deactivate(){clearInterval(timer);timer=null;panel?.remove();panel=null}
function register(){return window.TornUtilities?.register({id:ID,version:"0.2.0",activate,deactivate})}
if(!register())window.addEventListener("torn-utilities-ready",register,{once:true});
})();