// ==UserScript==
// @name         TU Slithering Streets
// @namespace    https://github.com/RelaxSweety/Torn-Scripts
// @version      0.2.6
// @description  Torn Utilities mobile-friendly Snake arcade
// @match        https://www.torn.com/*
// @grant        none
// @run-at       document-idle
// ==/UserScript==
(()=>{'use strict';const ID="torn-snake";let panel=null,canvas=null,ctx=null,timer=null,head=null,score=0,food=null,dir=[1,0],next=[1,0],snake=[],running=false;
const E=(tag,parent,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;parent.append(e);return e};
function spawn(){do{food=Math.floor(Math.random()*400)}while(snake.includes(food))}
function draw(){if(!ctx)return;ctx.fillStyle="#17232c";ctx.fillRect(0,0,320,320);ctx.fillStyle="#d6a950";ctx.fillRect(food%20*16,Math.floor(food/20)*16,15,15);ctx.fillStyle="#62c68b";for(const n of snake)ctx.fillRect(n%20*16,Math.floor(n/20)*16,15,15);panel.querySelector(".score").textContent="Score: "+score+" | Best: "+(localStorage.getItem("tu:snake:best")||0)}
function end(){running=false;clearInterval(timer);timer=null;const best=Math.max(score,Number(localStorage.getItem("tu:snake:best")||0));localStorage.setItem("tu:snake:best",best);try{const h=JSON.parse(localStorage.getItem("tu:snake:runs")||"[]");h.unshift({score,completed:new Date().toISOString()});localStorage.setItem("tu:snake:runs",JSON.stringify(h.slice(0,200)))}catch{}draw();panel?._statsUpdate?.()}
function tick(){dir=next;const x=snake[0]%20+dir[0],y=Math.floor(snake[0]/20)+dir[1],n=y*20+x;if(x<0||x>=20||y<0||y>=20||snake.slice(0,food===n?undefined:-1).includes(n)){end();return}snake.unshift(n);if(n===food){score++;spawn()}else snake.pop();draw()}
function turn(x,y){if(x===-dir[0]&&y===-dir[1])return;next=[x,y]}
function start(){clearInterval(timer);score=0;snake=[210,209,208];dir=[1,0];next=[1,0];spawn();running=true;draw();timer=setInterval(tick,125)}
function activate({mount,close}){panel=E("section",mount);panel.style.cssText="position:fixed;top:50%;left:50%;transform:translate(-50%,-50%);width:min(370px,95vw);max-height:90vh;overflow:auto;resize:both;background:#20252e;color:white;border:1px solid #888;border-radius:12px;padding:15px;min-width:260px;min-height:320px;height:min(660px,82vh);max-width:96vw;box-sizing:border-box;z-index:2147483647;font:14px system-ui";
const bar=E("div",panel);bar.style.cssText="display:flex;justify-content:space-between;align-items:center;gap:8px;margin-bottom:10px;cursor:move;touch-action:none;user-select:none";E("strong",bar,"Slithering Streets");const min=E("button",bar,"−");min.onclick=close;min.title="Minimize to TU";min.setAttribute("aria-label","Minimize Slithering Streets to TU");min.style.cssText="background:#344154;color:#fff;border:1px solid #657184;border-radius:6px;padding:0 12px;line-height:30px;font-size:22px;font-weight:bold;cursor:pointer";
let drag;bar.onpointerdown=e=>{if(e.target===min)return;const r=panel.getBoundingClientRect();drag=[e.clientX,e.clientY,r.left,r.top];panel.style.transform="none";panel.style.left=r.left+"px";panel.style.top=r.top+"px";bar.setPointerCapture(e.pointerId)};bar.onpointermove=e=>{if(!drag)return;panel.style.left=Math.max(0,drag[2]+e.clientX-drag[0])+"px";panel.style.top=Math.max(0,drag[3]+e.clientY-drag[1])+"px"};bar.onpointerup=()=>drag=null;bar.onpointercancel=()=>drag=null;
const grip=E("div",panel,"◢");grip.style.cssText="position:absolute;right:3px;bottom:2px;width:30px;height:30px;display:flex;align-items:end;justify-content:end;padding:3px;box-sizing:border-box;cursor:nwse-resize;touch-action:none;color:#d6b96a;font-size:21px;z-index:2";let resizing=null;grip.onpointerdown=e=>{e.preventDefault();const r=panel.getBoundingClientRect();resizing={x:e.clientX,y:e.clientY,w:r.width,h:r.height,l:r.left,t:r.top};panel.style.transform="none";panel.style.left=r.left+"px";panel.style.top=r.top+"px";panel.style.width=r.width+"px";panel.style.height=r.height+"px";grip.setPointerCapture(e.pointerId)};grip.onpointermove=e=>{if(!resizing)return;panel.style.width=Math.max(260,Math.min(innerWidth-resizing.l-8,resizing.w+e.clientX-resizing.x))+"px";panel.style.height=Math.max(320,Math.min(innerHeight-resizing.t-8,resizing.h+e.clientY-resizing.y))+"px"};grip.onpointerup=()=>resizing=null;grip.onpointercancel=()=>resizing=null;
const status=E("div",panel,"Ready to play");status.style.cssText="margin:6px 0;color:#d8dde5";E("p",panel).className="score";const arena=E("div",panel);arena.style.cssText="border:3px solid #d6b96a;border-radius:7px;background:#111a21;padding:5px;box-shadow:inset 0 0 0 1px #657184;margin:8px auto;width:100%;max-width:340px;box-sizing:border-box";canvas=E("canvas",arena);canvas.width=320;canvas.height=320;canvas.style.cssText="width:100%;aspect-ratio:1;display:block;touch-action:none;border:1px solid #425264;box-sizing:border-box";ctx=canvas.getContext("2d");
const statbox=E("div",panel);statbox.style.cssText="font-size:12px;color:#d8dde5;margin:8px 0";const history=E("div",panel);history.hidden=true;history.style.cssText="max-height:180px;overflow:auto;border:1px solid #657184;border-radius:6px;padding:8px;margin:6px 0";const show=E("button",panel,"Score History");show.style.cssText="background:#344154;color:#fff;border:1px solid #657184;border-radius:6px;padding:8px;cursor:pointer";show.onclick=()=>{history.hidden=!history.hidden;show.textContent=history.hidden?"Score History":"Hide History";panel._statsUpdate?.()};panel._statsUpdate=()=>{let h=[];try{h=JSON.parse(localStorage.getItem("tu:snake:runs")||"[]")}catch{}statbox.textContent="High score: "+(localStorage.getItem("tu:snake:best")||0)+" | Games played: "+h.length+" | Average: "+(h.length?Math.round(h.reduce((a,b)=>a+b.score,0)/h.length):0);if(!history.hidden){history.replaceChildren();if(!h.length)E("p",history,"No completed games yet.");for(const x of h)E("div",history,new Date(x.completed).toLocaleString()+" | Score: "+x.score)}};panel._statsUpdate();const controls=E("div",panel);controls.style.cssText="display:grid;grid-template-columns:repeat(3,1fr);gap:5px;max-width:240px;margin:8px auto";const button=(label,fn)=>{const b=E("button",controls,label);b.style.cssText="padding:10px;background:#344154;color:white;border:1px solid #657184;border-radius:6px;font:inherit;cursor:pointer";b.onclick=fn;return b};
button(" ",()=>{});button("▲",()=>turn(0,-1));button(" ",()=>{});button("◀",()=>turn(-1,0));button("▼",()=>turn(0,1));button("▶",()=>turn(1,0));const play=E("button",panel,"Start / Restart");play.style.cssText="background:#344154;color:#fff;border:1px solid #657184;border-radius:6px;padding:9px 14px;font:inherit;cursor:pointer";play.onclick=start;
const copy=E("button",panel,"Copy Game Summary");copy.style.cssText="background:#344154;color:#fff;border:1px solid #657184;border-radius:6px;padding:9px 14px;font:inherit;cursor:pointer;margin:8px 0 0 8px";copy.onclick=async()=>{let h=[];try{h=JSON.parse(localStorage.getItem("tu:snake:runs")||"[]")}catch{}const best=Number(localStorage.getItem("tu:snake:best")||0),avg=h.length?Math.round(h.reduce((a,b)=>a+b.score,0)/h.length):0;const latest=h[0];const identity=(()=>{const bad=/^(view profile|profile|player|my profile|view|account|user profile)$/i;const clean=v=>{v=(v||"").trim();return v.length<=32&&/^[a-zA-Z0-9_-]+$/.test(v)&&!bad.test(v)?v:""};const profileLinks=[...document.querySelectorAll('a[href*="profiles.php?XID="]')];const own=profileLinks.filter(el=>el.closest('header,[class*="header"],[class*="sidebar"],[class*="userInfo"],[class*="user-info"],[class*="topbar"]'));let name="";for(const el of own){name=clean(el.getAttribute("title"))||clean(el.getAttribute("aria-label"))||clean(el.textContent);if(name)break}if(!name){for(const selector of ['[class*="userName"]','[class*="username"]','[class*="playerName"]']){for(const el of document.querySelectorAll(selector)){name=clean(el.textContent);if(name)break}if(name)break}}const link=own[0]?.href||"https://www.torn.com/profiles.php";return {name,link}})();const msg=(identity.name||identity.link)+" played Slithering Streets for a score of "+(latest?latest.score:score);try{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(msg);status.textContent="Game summary copied — paste into Torn chat";return}}catch{}const field=E("textarea",panel,msg);field.style.cssText="display:block;width:100%;height:70px;margin-top:8px";field.select();let ok=false;try{ok=document.execCommand("copy")}catch{}status.textContent=ok?"Game summary copied — paste into Torn chat":"Select and copy the summary below";if(ok)setTimeout(()=>field.remove(),2000)};
panel.append(show,history);
const key=e=>{const d={ArrowUp:[0,-1],ArrowDown:[0,1],ArrowLeft:[-1,0],ArrowRight:[1,0],w:[0,-1],s:[0,1],a:[-1,0],d:[1,0]}[e.key];if(d){e.preventDefault();turn(...d)}};window.addEventListener("keydown",key);panel._cleanup=()=>window.removeEventListener("keydown",key);snake=[210,209,208];spawn();draw()}
function deactivate(){clearInterval(timer);timer=null;running=false;panel?._cleanup?.();panel?.remove();panel=null;canvas=null;ctx=null}
const register=()=>window.TornUtilities?.register({id:ID,version:"0.2.6",activate,deactivate});if(!register())window.addEventListener("torn-utilities-ready",register,{once:true});
})();